sudo: true

language: node_js
node_js:
  - 12

before_install:
  - yarn add codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
addons:
  sonarcloud:
    organization: "habil-github"

script:
  - sonar-scanner
